"use client";
import { useState } from "react";
import { useRef } from "react";
import { Flower2, ArrowRight } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { relationshipOptions } from "@/lib/config";
export default function KanyadaanExperience() {
  const [name, setName] = useState(""); const [relationship, setRelationship] = useState(""); const [flowers, setFlowers] = useState<number[]>([]); const [complete, setComplete] = useState(false);
  const relationshipRef = useRef<HTMLSelectElement>(null);
  const offer = () => { if (!name.trim() || !relationship) return; setFlowers((f) => [...f, Date.now()]); };
  const finish = () => { if (!flowers.length) return; setComplete(true); window.open("https://rzp.io/rzp/YTJ43AGG", "_blank", "noopener,noreferrer"); };
  const startAgain = () => { setName(""); setRelationship(""); setFlowers([]); setComplete(false); };
  return <section id="participate" className="section experience"><div className="section-heading centered"><p className="eyebrow">YOUR PLACE IN THE CEREMONY</p><h2>Offer a blessing</h2><p>Take a quiet moment to add your love to their new beginning.</p></div><div className="ceremony-card"><div className="steps"><div className={`step ${!name ? "active" : "complete"}`}><span>01</span><div><b>Your name</b><small>Let the couple know who is joining them</small></div></div><div className={`step ${name && !relationship ? "active" : relationship ? "complete" : ""}`}><span>02</span><div><b>Your relationship</b><small>Choose the bond you share</small></div></div><div className={`step ${relationship && !flowers.length ? "active" : flowers.length ? "complete" : ""}`}><span>03</span><div><b>Offer flowers</b><small>Place your symbolic blessing</small></div></div><div className={`step ${flowers.length ? "active" : ""}`}><span>04</span><div><b>Pay now</b><small>Complete Kanyadaan securely</small></div></div></div><div className="offering-panel"><div className="field-row"><label>Your name<input value={name} onChange={(e) => setName(e.target.value)} onBlur={() => { if (name.trim()) relationshipRef.current?.focus(); }} placeholder="e.g. Meera Sharma" /></label><label>Relationship<select ref={relationshipRef} value={relationship} onChange={(e) => setRelationship(e.target.value)}><option value="">Select one</option>{relationshipOptions.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="bowl-scene"><div className="flower-rain">{flowers.map((id) => <motion.span key={id} initial={{ y: -60, opacity: 0, rotate: 0 }} animate={{ y: 110, opacity: 1, rotate: 240 }} transition={{ duration: 1.4 }}>✿</motion.span>)}</div><div className="offering-bowl"><div className="bowl-flower">{flowers.length ? "✿ ✽ ❀" : "✧"}</div></div><p>{flowers.length ? "Your flowers are held with love." : "Your offering bowl awaits"}</p></div><div className="offering-actions"><button className="button primary" onClick={offer} disabled={!name.trim() || !relationship}><Flower2 size={17} /> Offer Flowers</button><button className="text-button" onClick={finish} disabled={!flowers.length}>Complete My Blessing <ArrowRight size={16} /></button></div></div></div><AnimatePresence>{complete && <motion.div className="completion" initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }}><div className="completion-icon">🙏</div><p className="eyebrow">धन्यवाद</p><h3>Your blessings have become part of this beautiful new beginning.</h3><p>May the couple&apos;s journey be filled with love, happiness and prosperity.</p><small className="payment-note">Razorpay opened in a new tab</small><button className="text-button" onClick={startAgain}>Offer another blessing</button></motion.div>}</AnimatePresence></section>;
}
