"use client";
import { useEffect, useState } from "react";
import { CalendarDays, Clock3, MapPin, Plus } from "lucide-react";
import { weddingConfig, weddingDateDisplay } from "@/lib/config";
function remaining() { const diff = Math.max(0, new Date(weddingConfig.weddingDate).getTime() - Date.now()); return { days: Math.floor(diff / 86400000), hours: Math.floor(diff / 3600000) % 24, minutes: Math.floor(diff / 60000) % 60, seconds: Math.floor(diff / 1000) % 60 }; }
const emptyCountdown = { days: 0, hours: 0, minutes: 0, seconds: 0 };
export default function WeddingDetails() { const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${weddingConfig.venue}, ${weddingConfig.city}`)}`; const [time, setTime] = useState(emptyCountdown); useEffect(() => { setTime(remaining()); const id = setInterval(() => setTime(remaining()), 1000); return () => clearInterval(id); }, []); const calendar = () => { const start = new Date(weddingConfig.weddingDate).toISOString().replace(/[-:]/g, "").split(".")[0] + "Z"; window.open(`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(`Wedding of ${weddingConfig.brideName} & ${weddingConfig.groomName}`)}&dates=${start}/${start}&location=${encodeURIComponent(weddingConfig.venue)}`, "_blank"); };
  return <section id="details" className="section section-cream details"><div className="section-heading centered"><p className="eyebrow">SAVE THE DATE</p><h2>Come celebrate with us</h2><p>We cannot wait to welcome you into this beautiful day.</p></div><div className="details-grid"><div className="detail-info"><div className="detail-item"><CalendarDays /><div><small>WEDDING CEREMONY</small><b>{weddingDateDisplay}</b></div></div><div className="detail-item"><Clock3 /><div><small>TIME</small><b>{weddingConfig.weddingTime}</b></div></div><a className="detail-item venue-link" href={mapUrl} target="_blank" rel="noreferrer" aria-label={`Open ${weddingConfig.venue}, ${weddingConfig.city} in Google Maps`}><MapPin /><div><small>VENUE</small><b>{weddingConfig.venue}<br />{weddingConfig.city}</b></div></a><button className="button outline" onClick={calendar}><Plus size={16} /> Add to Calendar</button></div><div className="countdown"><p>THE COUNTDOWN BEGINS</p><div className="count-grid">{Object.entries(time).map(([label, value]) => <div key={label}><strong>{String(value).padStart(2, "0")}</strong><span>{label}</span></div>)}</div><div className="lotus">❧</div></div></div></section>;
}
